modLoader="kotlinforforge"
loaderVersion="[1.11,)"
license="MIT"
issueTrackerURL="https://github.com/klikli-dev/theurgy/issues"

[[mods]]
modId="theurgy"
version="${file.jarVersion}"
displayName="Theurgy"
displayURL="https://www.curseforge.com/minecraft/mc-mods/theurgy"
logoFile="theurgy.png"
credits="""See https://github.com/klikli-dev/theurgy#licensing"""
authors="Kli Kli"
description='''
An open-source magic mod inspired by botania, thaumcraft and others.
'''


[[dependencies.theurgy]]
modId="patchouli"
mandatory=true
versionRange="[1.16.4-1.2-28,)"
side="BOTH"